version: "3.9"
services:
 api-service:
    image: jentelliekens/python-db-test
    ports:
      - "8000:8000"
    volumes:
      - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: