version: "3.9"
services:
 randomizer-service:
  image: JentelLiekens/project-kv-mechelen
  ports:
    - "8000:8000"
  volumes:
    - sqlite_useritems_volume:/code/sqlitedb

volumes:
  sqlite_useritems_volume: